const PixelScan = {
    FramedSprite,
    AABB,
    Vec2,
    Input,
    World,
    GroundController,
    FPSTracker,
    CPUTracker,
    ParallaxSprite,
    PerlinNoise,
    Camera,
    Hash,
    DebugCanvas,
    DynamicTree,
    extract,
};